#pragma once

#define DEFAULT_FONT						"맑은 고딕";
#define DEFAULT_FONT_SIZE					10

#define DEFAULT_CPU_ALERT					80
#define DEFUALT_RAM_ALERT					80
#define DEFAULT_RECV_ALERT					80
#define DEFAULT_SEND_ALERT					80
#define DEFAULT_HDD_ALERT					150

enum VS_STATUS {VS_STATUS_OK = 1, VS_STATUS_ERR,};
enum SUB_DIALOG { WRONG_DLG = 0, SUB_IMAGEMONITOR = 1, SUB_STATUSMONITOR, SUB_FINDCAR, SUB_MANAGER, };

/* Messages */
#define WM_INITIALIZE						WM_USER + 101
#define WM_CPUUSAGE_UPDATE					WM_USER + 201
#define WM_VSIMAGE_UPDATE					WM_USER + 211
#define WM_VSIMAGE_MANUAL_UPDATE			WM_USER + 212
#define WM_VSCLIENT_HEARTBEAT				WM_USER + 215
#define WM_VSCLIENT_CHANGESTATUS			WM_USER + 221
#define WM_VSCLIENT_CONFIG_RESPONSE			WM_USER + 231

/*Controls Position - LEFT, TOP*/
#define ID_MAINDLG_BTN_IMAGEMONITOR_LEFT	10
#define ID_MAINDLG_BTN_IMAGEMONITOR_TOP		100
#define ID_MAINDLG_BTN_STATUSMONITOR_LEFT	140
#define ID_MAINDLG_BTN_STATUSMONITOR_TOP	100
#define ID_MAINDLG_BTN_FINDCAR_LEFT			270
#define ID_MAINDLG_BTN_FINDCAR_TOP			100
#define ID_MAINDLG_BTN_MANAGER_LEFT			400
#define ID_MAINDLG_BTN_MANAGER_TOP			100
#define ID_MAINDLG_BANNER_TITLE_TOP			10

#define ID_MAINDLG_TIME_LEFT				30
#define ID_MAINDLG_TIME_TOP					50
#define ID_MAINDLG_TIME_RIGHT				ID_MAINDLG_TIME_LEFT + 300
#define ID_MAINDLG_TIME_BOTTOM				ID_MAINDLG_TIME_TOP + 30


#define ID_IMAGEMONITORDLG_BTN_1X1_BOTTOM	5
#define ID_IMAGEMONITORDLG_BTN_1X1_RIGHT	122
#define ID_IMAGEMONITORDLG_BTN_2X2_BOTTOM	5
#define ID_IMAGEMONITORDLG_BTN_2X2_RIGHT	94
#define ID_IMAGEMONITORDLG_BTN_3X3_BOTTOM	5
#define ID_IMAGEMONITORDLG_BTN_3X3_RIGHT	66
#define ID_IMAGEMONITORDLG_BTN_4X4_BOTTOM	5
#define ID_IMAGEMONITORDLG_BTN_4X4_RIGHT	38
#define ID_IMAGEMONITORDLG_BTN_5X5_RIGHT	10
#define ID_IMAGEMONITORDLG_BTN_5X5_BOTTOM	5

#define ID_IMAGEMONITORDLG_BTN_FLOOR_LEFT	10
#define ID_IMAGEMONITORDLG_BTN_FLOOR_BOTTOM	5
#define ID_IMAGEMONITORDLG_BTN_FLOOR_GAB	5


/*Controls ID*/
#define ID_MAINDLG_BTN_IMAGEMONITOR			101
#define ID_MAINDLG_BTN_STATUSMONITOR		102
#define ID_MAINDLG_BTN_FINDCAR				103
#define ID_MAINDLG_BTN_MANAGER				104
#define ID_IMAGEMONITOR_BTN_1X1				121
#define ID_IMAGEMONITOR_BTN_2X2				122
#define ID_IMAGEMONITOR_BTN_3X3				123
#define ID_IMAGEMONITOR_BTN_4X4				124
#define ID_IMAGEMONITOR_BTN_5X5				125
#define ID_IMAGEMONITOR_BTN_PAGE_LEFT		126
#define ID_IMAGEMONITOR_BTN_PAGE_RIGHT		127
#define ID_IMAGEMONITOR_BTN_INITIMAGE		128
/* ImageMonitorDlg Floor ID 151 ~ 160 Reserved */
#define ID_IMAGEMONITOR_BTN_FLOOR_START		151
#define ID_IMAGEMONITOR_BTN_FLOOR_END		160
/* StatusMonitorDlg Floor ID 161 ~ 170 Reserved */
#define ID_STATUSMONITOR_BTN_FLOOR_START	161
#define ID_STATUSMONITOR_BTN_FLOOR_END		170
/* VSIcon ID 201 ~ 300 Reserved */
#define ID_STATUSMONITOR_VSICON_START		201
#define ID_STATUSMONITOR_VSICON_END			300
/* CarFindDlg */
#define ID_CARFIND_BTN_FIND					301
#define ID_CARFIND_BTN_CLEARFILTER			302
#define ID_CARFIND_BTN_CLEARLIST			303

/*Dialog Position - LEFT, TOP*/
#define COMMON_SPACE						10
#define ID_MAINDLG_IMAGEMONITORDLG_LEFT		5
#define ID_MAINDLG_IMAGEMONITORDLG_TOP		140
#define ID_MAINDLG_IMAGEMONITORDLG_RIGHT_SPACE	300
#define ID_MAINDLG_IMAGEMONITORDLG_BOTTOM_SPACE	165
#define ID_MAINDLG_STATUSMONITORDLG_LEFT	5
#define ID_MAINDLG_STATUSMONITORDLG_TOP		140
#define ID_MAINDLG_FINDCARDLG_LEFT			5
#define ID_MAINDLG_FINDCARDLG_TOP			140
#define ID_MAINDLG_MANAGERDLG_LEFT			5
#define ID_MAINDLG_MANAGERDLG_TOP			140


/* Controls Position - FindCarDlg */
#define FINDCARDLG_GROUPBOX_BOTTOM_SPACE	10
#define FINDCARDLG_GROUPBOX_RIGHT_SPACE		10
#define FINDCARDLG_GROUPBOX_RESULT_LEFT		325
#define FINDCARDLG_LISTCTRL_RIGHT_SPACE		20
#define FINDCARDLG_LISTCTRL_BOTTOM_SPACE	45
#define FINDCARDLG_LISTCTRL_LEFT			335
#define FINDCARDLG_LISTCTRL_TOP_SPACE		30
#define FINDCARDLG_BTN_FIND_LEFT			20
#define FINDCARDLG_BTN_FIND_BOTTOM_SPACE	20
#define FINDCARDLG_BTN_CLEARLIST_LEFT_SPACE	345
#define FINDCARDLG_BTN_CLEARLIST_BOTTOM_SPACE	20
#define FINDCARDLG_BTN_CLEARFILTER_LEFT_SPACE	180

/* Controls Position - ManagerDlg */
#define MANAGERDLG_USER_ADJUSTHEGHT			240
#define MANAGERDLG_GROUPBOX_VS_WIDTH		790
#define MANAGERDLG_GROUPBOX_KIOSK_HEIGHT	400
#define MANAGERDLG_GROUPBOX_USER_WIDTH		350
#define MANAGERDLG_GROUPBOX_USER_HEIGHT		400
#define MANAGERDLG_GROUPBOX_PACKET_TOP		MANAGERDLG_GROUPBOX_USER_HEIGHT + 20
#define MANAGERDLG_STATIC_ID_LEFT			40
#define MANAGERDLG_STATIC_ID_TOP			40
#define MANAGERDLG_STATIC_PASS_TOP			65
#define MANAGERDLG_EDIT_ID_TOP				MANAGERDLG_STATIC_ID_TOP - 4
#define MANAGERDLG_EDIT_ID_LEFT				140
#define MANAGERDLG_EDIT_ID_RIGHT_SPACE		40
#define MANAGERDLG_EDIT_ID_HEIGHT			18
#define MANAGERDLG_EDIT_PASS_TOP			MANAGERDLG_EDIT_ID_TOP + 25
#define MANAGERDLG_EDIT_PASS_LEFT			MANAGERDLG_EDIT_ID_LEFT
#define MANAGERDLG_EDIT_PASS_RIGHT_SPACE	MANAGERDLG_EDIT_ID_RIGHT_SPACE
#define MANAGERDLG_EDIT_PASS_HEIGHT			MANAGERDLG_EDIT_ID_HEIGHT
#define MANAGERDLG_BTN_LOGIN_LEFT			100
#define MANAGERDLG_BTN_LOGIN_TOP			120
#define MANAGERDLG_REDIT_VS_BOTTOM_SPACE	COMMON_SPACE * 4
#define MANAGERDLG_BTN_ADDKIOSK_LEFT_SPACE	20
#define MANAGERDLG_BTN_REMOVEKIOSK_LEFT_SPACE	100
#define MANAGERDLG_BTN_ADDVS_LEFT_SPACE		20
#define MANAGERDLG_BTN_REMOVEVS_LEFT_SPACE	100
#define MANAGERDLG_BTN_REFRESHVS_RIGHT_SPACE	20
#define MANAGERDLG_BTN_REFRESHKIOSK_RIGHT_SPACE	20


#define FIND_ROWS_PER_PAGE					40

#define MAX_IP_LEN							16
#define MAX_LOCATION_LEN					10
#define MAX_FLOOR_LEN						4
#define MAX_SECTOR_LEN						2
#define MAX_TIME_LEN						23
#define MAX_RECOG_LEN						12
#define MAX_WIFI_LEN						50

#define VECTOR_RESERVE_SIZE					100

#define IMAGE_GRID_TOP_SPACE				20
#define IMAGE_GRID_BOTTOM_CAPTION_SIZE		34
#define IMAGE_GRID_TEXTCAPTION_SIZE			16
#define IMAGE_GRID_EDGE_SIZE				4

#define FLOOR_CAPTION_LEN					10
#define FLOOR_NAME_LEN						5
#define MAX_FLOOR_SIZE						10
#define MAX_AREA_LEN						4
#define MAX_VSID_LEN						4
#define MAX_INFO_LEN						200

/* Structures */
typedef struct _VSENSOR
{
	int			nVSID;
	int			nServerID;
	TCHAR		csFloor[MAX_FLOOR_LEN];
	TCHAR		csSector[MAX_SECTOR_LEN];
	TCHAR		csIP[MAX_IP_LEN];
	TCHAR		csLocation[MAX_LOCATION_LEN];
	int			nFloorIndex;
	CPoint		ptPosition;
	VS_STATUS	nStatus;
	TCHAR		csImagePath[MAX_PATH];
	TCHAR		csCarNum[MAX_RECOG_LEN];
	TCHAR		csCarSeeTime[MAX_TIME_LEN];
	TCHAR		csInfo[MAX_INFO_LEN];
}VSENSOR_t, *PVSENSOR_t;

typedef struct _KIOSK
{
	int			nKIOSKID;
	TCHAR		csLocation[MAX_LOCATION_LEN];
	TCHAR		csIP[MAX_IP_LEN];
	VS_STATUS	nStatus;
}KIOSK_t, *PKIOSK_t;

typedef struct _IMAGEBLOCKINFO
{
	int			nIndex;
	CRect		rectBlock;								/* 이미지 블럭의 위치 */
	CRect		rectImage;								/* 이미지 보여줄 이미지 블럭 내의 위치 */
	CRect		rectTextBox;							/* 텍스트 박스 위치 */
	TCHAR		csTime[MAX_TIME_LEN];					/* 차량번호 인식된 시각 */
	TCHAR		csRecogNum[MAX_RECOG_LEN];				/* 인식된 차량번호 */
	CBitmap		bmpImage;								/* 보여줄 비트맵 파일 */
	TCHAR		csBmpPath[MAX_PATH];					/* bmp파일 경로 */
	PVSENSOR_t	pVSensor;								/* VSensor 포인터 */
}IMAGEBLOCKINFO_t, *PIMAGEBLOCKINFO_t;

typedef struct _FLOORINFO
{
	TCHAR		csCaption[FLOOR_CAPTION_LEN];
	TCHAR		csFloorName[FLOOR_NAME_LEN];
	UINT		nIndex;
}FLOORINFO_t, *PFLOORINFO_t;

typedef struct _VSServerInfo
{
	TCHAR		csIP[ MAX_TIME_LEN ];
	TCHAR		csNetmask[ MAX_TIME_LEN ];
	TCHAR		csMonitorPrgName[ MAX_TIME_LEN ];
	TCHAR		csDBUser[ MAX_TIME_LEN];
	TCHAR		csDBPass[ MAX_TIME_LEN ];
	TCHAR		csDBDSN[ MAX_TIME_LEN];
	int			nID;
	UINT16		nTcpPort;
	UINT16		nUdpPort;
	int			nVSCount;
	int			nFloorCount;
	int			nImageWidth;
	int			nImageHeight;
	TCHAR		csImageSavePath[MAX_PATH];
	FLOORINFO_t	stFloor[MAX_FLOOR_SIZE];
	int			nDBUse;
	int			nRunMonitor;
	int			nMinCarSeeTime;
	int			nForceUpdateTime;
	TCHAR		csWIFI_IP[ MAX_TIME_LEN ];
	TCHAR		csSSID[ MAX_WIFI_LEN];
	TCHAR		csKEY[ MAX_WIFI_LEN];
	TCHAR		csAWS_HOST[ MAX_AWS_HOST_SIZE];
	UINT16		nAWS_Port;
	TCHAR		csAWS_ID[ MAX_AWS_ID_SIZE];
}VSSERVERINFO_t, *PVSSERVERINFO_t;

typedef struct _FindCarResult
{
	TCHAR		csDate[MAX_TIME_LEN];
	TCHAR		csFloor[FLOOR_NAME_LEN];
	TCHAR		csArea[MAX_AREA_LEN];
	TCHAR		csVSID[MAX_VSID_LEN];
	TCHAR		csRecogNum[MAX_RECOG_LEN];
	TCHAR		csBmpPath[MAX_PATH];
	TCHAR		csInfo[MAX_INFO_LEN];
}FINDCARRESULT_t, *PFINDCARRESULT_t;

struct FindVSID
{
public:
	int m_nVSID;
	bool operator()(VSENSOR_t* pVS) const
	{
		return pVS->nVSID == m_nVSID;
	}
};
