//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VS_Server.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VS_SERVER_DIALOG            102
#define IDS_ERR_MUTEX                   102
#define IDS_ERR_NOT_CREATE_OBJECT       103
#define IDS_ERR_CONTROL                 104
#define IDS_ERR_DB_COF                  105
#define IDS_ERR_DB_OPEN                 106
#define IDS_ERR_TRANSFER_CONF           107
#define IDS_ERR_TRANSFER_OPEN           108
#define IDS_ERR_VIEWER_CONF             109
#define IDS_ERR_NOT_ALIVE_CLIENT        110
#define IDS_ERR_RESP_TIMEOUT            111
#define IDS_RERUN_MONITORING_SERVER     112
#define IDS_ERR_SELECT_CLIENT_ID        113
#define IDS_ERR_CHG_VSID                114
#define IDS_ERR_CHG_VSIP                115
#define IDS_ERR_CHG_VSSUBNET            116
#define IDS_ERR_CHG_VSGATE              117
#define IDS_ERR_CHG_RUNMODE             118
#define IDS_ERR_CHG_SERVER_IP           119
#define IDS_ERR_CHG_SERVER_PORT         120
#define IDR_MAINFRAME                   128
#define IDD_Login                       129
#define IDD_Admin                       130
#define IDD_Search                      131
#define IDB_BIT_GLADE                   133
#define IDB_BIT_GREEN                   134
#define IDB_BIT_RED                     135
#define IDC_BTN_CLOSE                   1002
#define IDC_SERVERIP                    1004
#define IDC_TCPSTATE                    1005
#define IDC_SERVERIP2                   1006
#define IDC_LOGLIST                     1007
#define IDC_BTN_CLEAR                   1008
#define IDC_BTN_ETC3                    1011
#define IDC_BTN_ETC4                    1012
#define IDC_SERVER_ID                   1013
#define IDC_CLIENT_CNT                  1014
#define IDC_CLIENT_LIST                 1015
#define IDC_SELECTED_CLIENT             1016
#define IDC_BTN_ETC5                    1017
#define IDC_BTN_ETC6                    1018
#define IDC_BTN_WATCH                   1019
#define IDC_BTN_MAC                     1020
#define IDC_BTN_VOL                     1021
#define IDC_BTN_LED_SET                 1022
#define IDC_BTN_LED_GET                 1023
#define IDC_BTN_CALL_READY              1024
#define IDC_BTN_GPIO_GET                1025
#define IDC_BTN_GPIO_SET                1026
#define IDC_BTN_ETC8                    1027
#define IDC_BTN_CALL_READY_AWS          1028
#define IDC_BTN_ETC9                    1029
#define IDC_IMG_SEE_TIME                1032
#define IDC_IMAGE_BOX2                  1032
#define IDC_CHECK1                      1035
#define IDC_CHK_SAVE                    1035
#define IDC_BUTTON1                     1036
#define IDC_BTN_ETC7                    1036
#define IDC_EDIT3                       1038
#define IDC_SPK_STS                     1042
#define IDC_MIC_STS                     1043
#define IDC_BTN_STS                     1044
#define IDC_GPIO_STS                    1045
#define IDC_TIME                        1046
#define IDC_VERSION                     1047
#define IDC_BTN_SORT                    1048
#define IDC_LIST_DISCONNECT             1050
#define IDC_WACH_ALL                    1051
#define IDC_COM_VOL                     1052
#define IDC_LED_ON_CNT                  1053
#define IDC_LED_OFF_CNT                 1054
#define IDC_COM_ONOFF                   1055
#define IDC_LED_ALL                     1056
#define IDC_COM_GPIO_ONOFF              1057
#define IDC_COM_GPIO_TYPE               1058
#define IDC_COM_ONOFF2                  1059
#define IDC_COM_ONOFF3                  1060
#define IDC_E_PORT                      1061
#define IDC_E_SSID                      1062
#define IDC_E_KEY                       1063
#define IDC_E_PORT2                     1064
#define IDC_EDIT1                       1065
#define IDC_EDIT2                       1066
#define IDC_CHECK2                      1067
#define IDC_EDIT4                       1068
#define IDC_BUTTON2                     1069
#define IDC_BUTTON3                     1070
#define IDC_EDIT5                       1071
#define IDC_EDIT6                       1072
#define IDC_EDIT7                       1073
#define IDC_EDIT8                       1074
#define IDC_COM_ONOFF4                  1075
#define IDC_EDIT9                       1076
#define IDC_EDIT10                      1077
#define IDC_EDIT11                      1078
#define IDC_EDIT12                      1079
#define IDC_COM_ONOFF5                  1080
#define IDC_BUTTON4                     1081
#define IDC_EDIT13                      1082
#define IDC_EDIT14                      1083
#define IDC_EDIT15                      1084
#define IDC_EDIT16                      1085
#define IDC_COM_ONOFF6                  1086
#define IDC_EDIT17                      1087
#define IDC_EDIT18                      1088
#define IDC_EDIT19                      1089
#define IDC_EDIT20                      1090
#define IDC_COM_ONOFF7                  1091
#define IDC_EDIT21                      1092
#define IDC_EDIT22                      1093
#define IDC_EDIT23                      1094
#define IDC_EDIT24                      1095
#define IDC_COM_ONOFF8                  1096
#define IDC_EDIT25                      1097
#define IDC_EDIT26                      1098
#define IDC_EDIT27                      1099
#define IDC_EDIT28                      1100
#define IDC_COM_ONOFF9                  1101
#define IDC_COM_ONOFF10                 1102
#define IDC_COM_ONOFF11                 1103
#define IDC_COM_ONOFF12                 1104
#define IDC_COM_ONOFF13                 1105
#define IDC_COM_ONOFF14                 1106
#define IDC_COM_ONOFF15                 1107
#define IDC_PLAY_AUDIO                  1108
#define C_E_AWS_HOST                    1109
#define C_E_AWS_ID                      1110
#define IDC_E_AWS_PORT                  1111
#define IDC_PUB                         1112
#define IDC_DEV_NUM                     1113
#define IDC_BUTTON5                     1114
#define IDC_EDIT41                      1115
#define IDC_EDIT29                      1116
#define IDC_EDIT30                      1117
#define IDC_EDIT31                      1118
#define IDC_EDIT32                      1119
#define IDC_COM_ONOFF16                 1120
#define IDC_EDIT33                      1121
#define IDC_EDIT34                      1122
#define IDC_EDIT35                      1123
#define IDC_EDIT36                      1124
#define IDC_COM_ONOFF17                 1125
#define IDC_EDIT37                      1126
#define IDC_EDIT38                      1127
#define IDC_EDIT39                      1128
#define IDC_EDIT40                      1129
#define IDC_COM_ONOFF18                 1130
#define IDC_COM_ONOFF19                 1131
#define IDC_COM_ONOFF20                 1132
#define IDC_COM_ONOFF21                 1133
#define IDC_BUTTON6                     1134
#define IDC_BUTTON7                     1135
#define IDC_EDIT42                      1136
#define IDC_BUTTON8                     1137
#define IDC_BUTTON9                     1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
